schemaVersion: '2.0.0' # Make sure to test the latest schema version
metadataTest:
  labels:
    - key: 'vendor'
      value: 'vendor1'
  exposedPorts: ["8080"]
  cmd: ["catalina.sh", "run"]  
fileExistenceTests:
- name: 'Root'
  path: '/usr/local/tomcat/webapps/sample.war'
  shouldExist: true
  permissions: '-rw-r--r--' 
